### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ValZapod** [CHEF-KOCH/nVidia-modded-Inf#1]
Hello! I have some questions. First I suppose this patch is not included https://github.com/keylase/nvidia-patch
Can anything be done in nvidea about this? I have a WTF moment.

Is HD audio driver not installed through geforce experience? Why do you need to integrate it?

"New Power management profiles" I don't have them. Why? I have latest DCH drivers and control panel from microsoft store.

**Comment by CHEF-KOCH** [comment]
## About nVidia patches
I'm not permitted to upload manipulated Linux/Windows files this would be against GitHub ToS because I never asked nVidia to give me permission to do so. DeltaFox is a known cracker and I don't think he has permission ([the restriction is a license thingy](https://devtalk.nvidia.com/default/topic/800942/gpu-accelerated-libraries/session-count-limitation-for-nvenc-no-maxwell-gpus-with-2-nevenc-sessions-/post/4562315/#4562315)) to upload patched files, that's why you have to patch it yourself. No there is nothing for me to do even if I wanted to. 

## Can anything done about it?
Yes, you could ask nVidia and create an issue ticket, [the answer will be the same](https://devtalk.nvidia.com/default/topic/993372/general-discussion/number-of-simultaneous-video-decoders/), `NO` because that is still a license thing (as mentioned above). I personally wonder why nVidia didn't take down the whole repository since this is [even mentioned on Wikipedia](https://en.wikipedia.org/wiki/Nvidia_NVENC) and clearly violates their license. Don't get me wrong I'm happy it's still hosted on GitHub.

## Why is HD Audio integrated?
HD Audio is a part of the normal driver package. I included it because it's not that heavy on file size + it can be useful and quickly enabled/disabled under "Sounds". 

## New Power management profiles
From what I know the new power management profiles are only visible if you meet specific requirements, DCH + Laptop GPU. However you can still use nVidia Inspector with Standard/DCH drivers to "unlock" it. 

![fffff](https://user-images.githubusercontent.com/727123/55994857-2fa8be00-5cb3-11e9-9032-262739c78a11.png)

But I see no point in switching to another power profile because a) nVidia will very soon change it again and b) the new profiles have lots of problems. 

I hope this answers all your questions.

**Comment by ValZapod** [comment]
Indeed.
