### ISSUE TITLE
Tier 1.1 (VRS at least) already working on 441.41?

### ISSUE THREAD

**Issue by ValZapod** [CHEF-KOCH/nVidia-modded-Inf#11]
@CHEF-KOCH See https://www.3dmark.com/vrs/4340 and that 
https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/325520/microsoft-blogs-new-dx-12-features-for-2020/

**Comment by CHEF-KOCH** [comment]
Official Tier "news tracker":
- https://news.developer.nvidia.com/dxr-tier-1-1/

I already posted it under 441.41 "own findings".

But everything you need to know in a nutshell:
- Tier 1.1 needs 20H1 (to be expected 12.12.2019 - rollout for everyone will be later).
- No there aren't any benefits using Tier 1.1  right now, it also will take months to fix bigger bugs and introduce the rest like [PIX](https://devblogs.microsoft.com/directx/dred-v1-2-supports-pix-marker-and-event-strings-in-auto-breadcrumbs/).
- `DISM /online /add-capability /capabilityname:tools.graphics.directx~~~~0.0.1.0` works (to get the [new D3DConfig.exe tool](https://devblogs.microsoft.com/directx/d3dconfig-a-new-tool-to-manage-directx-control-panel-settings/) in 1909, however, the functions are crippled and incomplete)

## Will current DXR hardware (as in, RTX Geforces of Turing) support Tier 1.1? Or is this reserved for next year's RTX cards?

> Developers targeting NVIDIA RTX GPUS will be able to take the greatest advantage of Microsoft’s software improvements, given the product range’s RT Cores for accelerating ray tracing and hardware support for mesh shaders. 

> Does VRS works with 441.41

No, since 441.41 is not an official nVidia 20H1 driver. My advice is to wait.

**Comment by ValZapod** [comment]
@CHEF-KOCH Hey, no! 1909 is reported by 3dmark as supporting Tier 1.1! https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/325520/microsoft-blogs-new-dx-12-features-for-2020/2332570/

**Comment by CHEF-KOCH** [comment]
Good, for 3Dmark (last updated [25. Sept. 2019](https://benchmarks.ul.com/3dmark/whats-new)), not "official" 1909 nor 20H1 ready. 

The readings are incorrect. There is no support for 1909.

**Comment by ValZapod** [comment]
@CHEF-KOCH It does support VRS. https://www.3dmark.com/vrs/4340 Any comment how is this possible?

**Comment by CHEF-KOCH** [comment]
It's not possible, end of disucssion.
