### ISSUE TITLE
[INFO] Removed content that may break user experience

### ISSUE THREAD

**Issue by levicki** [CHEF-KOCH/nVidia-modded-Inf#13]
Hello, this is not a bug report, just a FYI.

This is in your batch `remove-nvidia-bloat.bat`:
```
rd /s /q Display.Optimus
rd /s /q MSVCRT
rd /s /q NGXCore
```
As far as I know, removing the following items will break some functionality for some of the users:

1. Display.Optimus - on mobile drivers may affect the ability to use switchable graphics
2. MSVCRT - on older operating systems (Win7 and Win8.1) and clean installs removing it may stop NVCPL and/or drivers from working
3. NGXCore - removing this will prevent RTX users from using DLSS

Furthermore, newer drivers also contain PPC and NVPCF folders, PPC is a driver for USB-C port on some card models such as RTX 2080 Ti, and NVPCF is a driver for NVIDIA plafrom controllers.

Hopefully you find this information useful.

**Comment by CHEF-KOCH** [comment]
Hey, every feedback which is not "low effort" is welcome and appreciated!

I'm well aware of those things, that's why I wrote the docs. However, I agree that a batch is not the best way to remove components, because that depends on own user needs. There is basically nothing I can do here except:

* Providing for every user case a batch file.
* Re-write the script to PowerShell and implement several checks like which GPU is in use etc. The thing is we already have such "tools", already, it's called "NVSlimmer". This basically gives the user the ability to remove the stuff which he does not need, it would be possible to do the same via PowerShell GUI but I don't see why I should imitate NVSlimmer.

Both things are options, NVIDIA itself also provides something like this (except the telemetry part) in their own setup.exe, from there you basically choose what to install and what not. When I wrote the batch file NVIDIA wasn't forced by GPDR/DSGVO to do that, this changed now with new "data privacy laws". The telemetry itself can be op-out, it's IMHO not the correct way but there is the option.

What I can do is to link to the documents within the batch file so that the user know what he removes exactly and what is really needed (for him).

**Comment by levicki** [comment]
Hello again.

Thanks for considering my feedback. From what I know, most of those things I mentioned won't get installed if setup itself determines they are not needed (unlike GeForce Experience, Telemetry, and some other assorted junk).

As for removing stuff I have my own tool for downloading and extracting drivers to what I consider necessary so I am not a target audience for this anyway.

**Comment by levicki** [comment]
Well I guess I can help you out a bit by explaining what I am doing. I wrote a C# app which downloads and unpacks the driver without things I personally consider useless. Here is a regex filter which I use when extracting NVIDIA driver package:

    "^(Display\.(Driver|Optimus)|HDAudio|MSVCRT|NGXCore|NVI2|PhysX|PPC).*$|^GFExperience\\(PrivacyPolicy\\PrivacyPolicy_[a-z]{2}\-[A-Z]{2,3}\.htm|EULA.html|FunctionalConsent_[a-z]{2}\-[A-Z]{2,3}\.txt)$|^(ListDevices|license|EULA)\.txt$|^setup\.(cfg|exe)$"

Resulting extracted installation will work for most users save those who use 3D Vision or platform controllers (that can be restored easily by changing regex), and it does not need setup.cfg nor .inf changes. However, to my knowledge, it does not disable in-driver telemetry and it doesn't remove NVIDIA Display Container LS.

Let me know if you need any clarifications.

**Comment by CHEF-KOCH** [comment]
## Okay 
The Setup.exe was several times flawed and installed stuff which was not selected/detected, that was the idea behind "blindly" removing files/folders etc.

The regex example is pretty much pointless because EULA.txt (one example) never change the name nor the destination, same goes for pretty much everything unless nVidia removes or add new features. I see not much of a point to use regex instead of listening the whole folders (this way the user which is not experienced with coding understands easier what is going on).

However, I get your point that there should be an option/question which "core" components you need, for you 3D Vision seems to play a role (or was mentioned as example case). For me I do not need it. So I take the point and might add some checks to the batch files, but that's all I can do.

## App
@K4onashi wanted to write an app, I do not want to spoil something but from what I've heard it might include the following main features:

- Downloads latest NVIDIA driver (_maybe?_) (Standard/DCH detection, option)
- Remove bloatware (extraction) with options
- Unattended option (_maybe_) for "batch removal" or via predefined profiles (_maybe_)
- Include NVIDIA patch (see Readme.md what the patch does and the source code) (_maybe_)

Give him a follow, and we will know more pretty soon.

If nothing changes I'm going to change my bat file, as already mentioned or do a powershell script with some more "candy" in it.

**Comment by K4onashi** [comment]
I have already started development. It's going well and in early stages. Right now I'm working on the language system, but have all core elements ready for testing. 

A rough mew system on how to check for a newer version has been implemented.

Thanks.

**Comment by levicki** [comment]
@CHEF-KOCH You said above:

> The regex example is pretty much pointless because EULA.txt (one example) never change the name nor the destination

Which makes me doubt whether you really understand how that regex works.

During extraction of each file from the setup archive I match the path of the file being extracted to the regex. If it matches, then it gets extracted. It is a fast shorthand for comparing against the list of files you want to extract -- you just match against a single regex which should be faster though I admit it might be harder to maintain for those not trained in regex use.

Plain text equivalent of my regex is:
```
Display.Driver\*.*
Display.Optimus\*.*
HDAudio\*.*
MSVCRT\*.*
NGXCore\*.*
NVI2\*.*
PhysX\*.*
PPC\*.*
GFExperience\PrivacyPolicy\PrivacyPolicy_??-???.htm
GFExperience\PrivacyPolicy\EULA.html
GFExperience\PrivacyPolicy\FunctionalConsent_??-???.txt
ListDevices.txt
license.txt
EULA.txt
setup.cfg
setup.exe
```
Regarding this:

> Custom archive extraction without third-party unzippers like e.g. WinRAR

IMO, assuming you are writing code in C#, using SevenZipSharp is out of the question because it doesn't work with latest 7-Zip DLL, it is buggy, and slow, not to mention that it can't unpack .EXE directly. My solution was to take [bit7z](https://github.com/rikyoz/bit7z) and write a managed wrapper in C++/CLR.

As for update check, there will be one potential problem -- namely, I haven't found a way how to programmatically detect whether Standard or DCH driver is installed, not to mention how to distinguish between Game Ready and Studio.

**Comment by Espionage724** [comment]
I have a laptop with Optimus (GTX 1060 + Intel UHD 630). I noticed the Optimus folder missing from this installer, but Optimus still seems to function fine (can select which GPU to use, and games can use the NVIDIA GPU no problem).

**Comment by Squall-Leonhart** [comment]
NVCPL doesn't use VCRT, it uses the OS CRT

**Comment by Squall-Leonhart** [comment]
@CHEF-KOCH  came across a number of interestingly versioned audio drivers that hint at the existance of 455 branch drivers,

rather than use their usual 1.x.xx.xx format (ie, 1.3.38.26) they are using a displaydriver version string

DriverVer = 04/18/2020,27.21.14.5509
DriverVer = 04/18/2020,27.21.14.5513

the actual nvhda.sys is versioned 1.3.38.28 though.
