### ISSUE TITLE
Installing older drivers on NVIDIA GTX 16 SUPER series cards

### ISSUE THREAD

**Issue by Morph1984** [CHEF-KOCH/nVidia-modded-Inf#15]
I would like to install the 425.31 drivers on my GTX 1650 SUPER for debugging a Turing OpenGL bug that got introduced at the 430 driver series and above. When I tried modifying my driver INF files, the installation succeeded however windows stopped the driver from initializing (Code 43 error), is there a way to workaround that?

Also, I tried using the INF provided in the INF mod (universal), and that just crashes the installer during the `Installing Graphics Driver` step.

Note: I used DDU and disabled automatic driver downloads through group policy, and also turned off driver signature enforcement.

**Comment by CHEF-KOCH** [comment]
There is no workaround, if the driver does not at least add support for the card itself then you can manipulate the .INF all day long, it will not work, because the .INF basically only adds the card as "detectable" to the setup (Windows installer routine) which means the "real driver support" comes from the .dll files, which I have no permission to mod (even if I wanted to nVidia would close this project ASAP). 

You can report the bugs over [here](https://forms.gle/kJ9Bqcaicvjb82SdA).
