### ISSUE TITLE
NSD vs. WHQL vs. GRD?

### ISSUE THREAD

**Issue by fluffypony** [CHEF-KOCH/nVidia-modded-Inf#30]
**I'm submitting a ...** 
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[x ] Documentation issue or request
```

**Current behavior**
The README has a section entitled "SD, CD, GRD, DCH or Standard drivers?", but then only covers DCH vs. Standard.

**Expected or/and desired behavior**
There are a plethora of releases, some of which have a large set of assets. Determining which to use should be explained in the README. If the answer is "just use the most recent release" then that's fine too, but should be noted in the "short answer" section of the README.

**Comment by CHEF-KOCH** [comment]
I personally give rats shit about Studio Driver (SD), that been said I never inspected them myself. That's why it's not covered in the Readme.md. I typically never install SD myself, I repack them and that's it. I tested them once to debunk the performance myth but that was it.

[According to this article](https://www.thefpsreview.com/2019/08/12/nvidia-studio-driver-vs-geforce-game-ready-driver-performance/8/) the game performance is identical compared to GRD. I'm not sure about the "Creative Applications" part or what does that even means, because the driver loads specific application/game profiles and this is not special, if you call Adobe.exe, Adobe.exe or call it "an creators app", you will see no difference. 

I personally see "Creators Drivers" or "Studio Drivers" as marketing gag from nVidia without and details what exactly is been improved nor do I see evidence that this has any pros/cons compared to Game Ready Drivers.

Its similar game with DCH. Except that MS decided here to "introduce a new driver format" (no benefit for customers) and call it "new", it causes confusion and in most cases "Standard" drivers doing the same job without going trough the Windows Store thing.

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/nVidia-modded-Inf/commit/af4e0832b9367124db6b70fdeea1e4bf30acad6d

**Comment by fluffypony** [comment]
@CHEF-KOCH awesome, thanks so much for that, that's much clearer:) Thanks again for all your effort, it is greatly appreciated!
