### ISSUE TITLE
NVIDIA GeForce GTX 860M is GameOver?

### ISSUE THREAD

**Issue by laincat** [CHEF-KOCH/nVidia-modded-Inf#7]

**Comment by CHEF-KOCH** [comment]
> NVIDIA GeForce GTX 860M is GameOver? 

To quickly answer your question, the [860M is still supported](https://www.geforce.com/drivers#start-search). 

Select "GeForce | GEForce 800M Series (Notebooks) | GeForce GTX 860M | Windows 10 64-bit | English (US) | Standard | All" and you see (right now) v436.15 from Aug. 27, 2019.


![ddsffs](https://user-images.githubusercontent.com/727123/64515710-a090e800-d2dc-11e9-94b1-24df81e20415.png)


Because I often get asked which cards/products are EOL/legacy I will list them here and update it whenever nVidia to decided to drop support for xyz GPU/product.

Legacy nVidia products drivers are (this means there is no way to "mod" them since nVidia removed support from the source code completely). nVidia did this for multiple reasons, driver source would be incredible large, support reasons, etc)

* NVIDIA Business Platform Drivers
* Zalman Stereoscopic 3D Driver
* ULi Drivers
* DualTV
* NVTV
* WDM
* RIVA TNT, RIVA TNT2, GeForce 256 and GeForce 2 series
* GeForce 2 series, GeForce 3 series and GeForce 4 series, nForce 1 - 7
* GeForce FX & MX series
* GeForce 6 series and GeForce 7 series
* Tesla 1 and 2-based, i.e. GeForce 8 series – GeForce 300 series
* Fermi, i.e. GeForce 400 series – GeForce 500 series

Still supported products are:
* 600 + 700/900 – RTX 20/TITAN RTX Series/Super
* 800M + 900M/10M – GTX 16/RTX 20 Series (Notebooks)
